format = """\n
[](#DA627D)\
$directory\
[](fg:#DA627D bg:#FCA17D)\
$git_branch\
$git_status\
[](fg:#FCA17D bg:#33658A)\
$time\
[ ](fg:#33658A)\n
$golang\
$java\
$nodejs\
$docker_context\
$python\

[  ](fg:yellow)\
"""

[directory]
style = "bg:#DA627D"
format = "[  $path ]($style)"
truncation_length = 2
truncation_symbol = "…/"

[docker_context]
symbol = " "
style = "bg:#06969A"
format = """[](#86BBD8)[ $symbol $context ]($style))[ ](fg:#86BBD8)\n\n"""

[git_branch]
symbol = ""
style = "bg:#FCA17D"
format = '[ $symbol $branch ]($style)'

[git_status]
modified = "󱦹 "
untracked = "󰂑 "
style = "bg:#FCA17D"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#86BBD8"
format = """[](#86BBD8)[ $symbol ($version) ]($style)[ ](fg:#86BBD8)\n\n"""

[java]
symbol = " "
style = "bg:#86BBD8"
format = """[](#86BBD8)[ $symbol ($version) ]($style)[ ](fg:#86BBD8)\n\n"""

[nodejs]
symbol = ""
style = "bg:#86BBD8"
format = """[](#86BBD8)[ $symbol ($version) ]($style)[ ](fg:#86BBD8)\n\n"""

[python]
style = "bg:yellow"
symbol = " "
format = """[](yellow)[ $symbol ($version) ]($style)[ ](fg:yellow)\n\n"""

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[  $time ]($style)'



